const items = [
    {
        id: '001',
        name: 'Wireless Headphones',
        image: 'https://example.com/images/headphones.jpg',
        rating: 4.5,
        price: 59.99,
    },
    {
        id: '002',
        name: 'Smart Watch',
        image: 'https://example.com/images/smartwatch.jpg',
        rating: 4.2,
        price: 129.99,
    },
    {
        id: '003',
        name: 'Gaming Mouse',
        image: 'https://example.com/images/gaming-mouse.jpg',
        rating: 4.7,
        price: 39.99,
    },
    {
        id: '004',
        name: 'Bluetooth Speaker',
        image: 'https://example.com/images/speaker.jpg',
        rating: 4.3,
        price: 45.5,
    },
    {
        id: '005',
        name: '4K Monitor',
        image: 'https://example.com/images/monitor.jpg',
        rating: 4.6,
        price: 299.99,
    },
    {
        id: '006',
        name: 'Mechanical Keyboard',
        image: 'https://example.com/images/keyboard.jpg',
        rating: 4.8,
        price: 79.95,
    },
    {
        id: '007',
        name: 'External SSD 1TB',
        image: 'https://example.com/images/ssd.jpg',
        rating: 4.4,
        price: 109.99,
    },
    {
        id: '008',
        name: 'Noise Cancelling Earbuds',
        image: 'https://example.com/images/earbuds.jpg',
        rating: 4.1,
        price: 89.99,
    },
    {
        id: '009',
        name: 'Portable Charger',
        image: 'https://example.com/images/charger.jpg',
        rating: 4.2,
        price: 29.99,
    },
    {
        id: '010',
        name: 'Smartphone Gimbal',
        image: 'https://example.com/images/gimbal.jpg',
        rating: 4.5,
        price: 119.99,
    },
    {
        id: '011',
        name: 'Wireless Router',
        image: 'https://example.com/images/router.jpg',
        rating: 4.0,
        price: 89.99,
    },
    {
        id: '012',
        name: 'Fitness Tracker',
        image: 'https://example.com/images/fitness-tracker.jpg',
        rating: 4.3,
        price: 49.99,
    },
    {
        id: '013',
        name: 'Laptop Stand',
        image: 'https://example.com/images/laptop-stand.jpg',
        rating: 4.6,
        price: 34.99,
    },
    {
        id: '014',
        name: 'Webcam 1080p',
        image: 'https://example.com/images/webcam.jpg',
        rating: 4.4,
        price: 54.99,
    },
    {
        id: '015',
        name: 'Gaming Chair',
        image: 'https://example.com/images/gaming-chair.jpg',
        rating: 4.7,
        price: 199.99,
    },
]

export default items
